# Exercise 1

### Step 1. Go to https://www.kaggle.com/openfoodfacts/world-food-facts/data

### Step 2. Download the dataset to your computer and unzip it.

### Step 3. Use the tsv file and assign it to a dataframe called food

In [59]:
import pandas as pd
import numpy as np
import os
import kagglehub
# Download latest version
path = kagglehub.dataset_download("openfoodfacts/world-food-facts")
file_path = '/Users/alexanderfrankow/.cache/kagglehub/datasets/openfoodfacts/world-food-facts/versions/5/en.openfoodfacts.org.products.tsv'
food = pd.read_table(file_path, sep="\t",low_memory=False)
food.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,0000000003087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000004530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,0000000004559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,0000000016087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,0000000016094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 4. See the first 5 entries

In [60]:
food.head(5)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,0000000003087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000004530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,0000000004559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,0000000016087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,0000000016094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5. What is the number of observations in the dataset?

In [61]:
print(f" the dataset has {food.shape[0]} observations")

 the dataset has 356027 observations

### Step 6. What is the number of columns in the dataset?

In [62]:
print(f" the dataset has {food.shape[1]} columns")

 the dataset has 163 columns

### Step 7. Print the name of all the columns.

In [63]:
counter = 0 
for elem in food.columns:
    print(f"Name of column {counter} is: {elem}")
    counter += 1

Name of column 0 is: code
Name of column 1 is: url
Name of column 2 is: creator
Name of column 3 is: created_t
Name of column 4 is: created_datetime
Name of column 5 is: last_modified_t
Name of column 6 is: last_modified_datetime
Name of column 7 is: product_name
Name of column 8 is: generic_name
Name of column 9 is: quantity
Name of column 10 is: packaging
Name of column 11 is: packaging_tags
Name of column 12 is: brands
Name of column 13 is: brands_tags
Name of column 14 is: categories
Name of column 15 is: categories_tags
Name of column 16 is: categories_en
Name of column 17 is: origins
Name of column 18 is: origins_tags
Name of column 19 is: manufacturing_places
Name of column 20 is: manufacturing_places_tags
Name of column 21 is: labels
Name of column 22 is: labels_tags
Name of column 23 is: labels_en
Name of column 24 is: emb_codes
Name of column 25 is: emb_codes_tags
Name of column 26 is: first_packaging_code_geo
Name of column 27 is: cities
Name of column 28 is: cities_tags
Name of column 29 is: purchase_places
Name of column 30 is: stores
Name of column 31 is: countries
Name of column 32 is: countries_tags
Name of column 33 is: countries_en
Name of column 34 is: ingredients_text
Name of column 35 is: allergens
Name of column 36 is: allergens_en
Name of column 37 is: traces
Name of column 38 is: traces_tags
Name of column 39 is: traces_en
Name of column 40 is: serving_size
Name of column 41 is: no_nutriments
Name of column 42 is: additives_n
Name of column 43 is: additives
Name of column 44 is: additives_tags
Name of column 45 is: additives_en
Name of column 46 is: ingredients_from_palm_oil_n
Name of column 47 is: ingredients_from_palm_oil
Name of column 48 is: ingredients_from_palm_oil_tags
Name of column 49 is: ingredients_that_may_be_from_palm_oil_n
Name of column 50 is: ingredients_that_may_be_from_palm_oil
Name of column 51 is: ingredients_that_may_be_from_palm_oil_tags
Name of column 52 is: nutrition_grade_uk
Name of column 53 is: nutrition_grade_fr
Name of column 54 is: pnns_groups_1
Name of column 55 is: pnns_groups_2
Name of column 56 is: states
Name of column 57 is: states_tags
Name of column 58 is: states_en
Name of column 59 is: main_category
Name of column 60 is: main_category_en
Name of column 61 is: image_url
Name of column 62 is: image_small_url
Name of column 63 is: energy_100g
Name of column 64 is: energy-from-fat_100g
Name of column 65 is: fat_100g
Name of column 66 is: saturated-fat_100g
Name of column 67 is: -butyric-acid_100g
Name of column 68 is: -caproic-acid_100g
Name of column 69 is: -caprylic-acid_100g
Name of column 70 is: -capric-acid_100g
Name of column 71 is: -lauric-acid_100g
Name of column 72 is: -myristic-acid_100g
Name of column 73 is: -palmitic-acid_100g
Name of column 74 is: -stearic-acid_100g
Name of column 75 is: -arachidic-acid_100g
Name of column 76 is: -behenic-acid_100g
Name of column 77 is: -lignoceric-acid_100g
Name of column 78 is: -cerotic-acid_100g
Name of column 79 is: -montanic-acid_100g
Name of column 80 is: -melissic-acid_100g
Name of column 81 is: monounsaturated-fat_100g
Name of column 82 is: polyunsaturated-fat_100g
Name of column 83 is: omega-3-fat_100g
Name of column 84 is: -alpha-linolenic-acid_100g
Name of column 85 is: -eicosapentaenoic-acid_100g
Name of column 86 is: -docosahexaenoic-acid_100g
Name of column 87 is: omega-6-fat_100g
Name of column 88 is: -linoleic-acid_100g
Name of column 89 is: -arachidonic-acid_100g
Name of column 90 is: -gamma-linolenic-acid_100g
Name of column 91 is: -dihomo-gamma-linolenic-acid_100g
Name of column 92 is: omega-9-fat_100g
Name of column 93 is: -oleic-acid_100g
Name of column 94 is: -elaidic-acid_100g
Name of column 95 is: -gondoic-acid_100g
Name of column 96 is: -mead-acid_100g
Name of column 97 is: -erucic-acid_100g
Name of column 98 is: -nervonic-acid_100g
Name of column 99 is: trans-fat_100g
Name of column 100 is: cholesterol_100g
Name of column 101 is: carbohydrates_100g
Name of column 102 is: sugars_100g
Name of column 103 is: -sucrose_100g
Name of column 104 is: -glucose_100g
Name of column 105 is: -fructose_100g
Name of column 106 is: -lactose_100g
Name of column 107 is: -maltose_100g
Name of column 108 is: -maltodextrins_100g
Name of column 109 is: starch_100g
Name of column 110 is: polyols_100g
Name of column 111 is: fiber_100g
Name of column 112 is: proteins_100g
Name of column 113 is: casein_100g
Name of column 114 is: serum-proteins_100g
Name of column 115 is: nucleotides_100g
Name of column 116 is: salt_100g
Name of column 117 is: sodium_100g
Name of column 118 is: alcohol_100g
Name of column 119 is: vitamin-a_100g
Name of column 120 is: beta-carotene_100g
Name of column 121 is: vitamin-d_100g
Name of column 122 is: vitamin-e_100g
Name of column 123 is: vitamin-k_100g
Name of column 124 is: vitamin-c_100g
Name of column 125 is: vitamin-b1_100g
Name of column 126 is: vitamin-b2_100g
Name of column 127 is: vitamin-pp_100g
Name of column 128 is: vitamin-b6_100g
Name of column 129 is: vitamin-b9_100g
Name of column 130 is: folates_100g
Name of column 131 is: vitamin-b12_100g
Name of column 132 is: biotin_100g
Name of column 133 is: pantothenic-acid_100g
Name of column 134 is: silica_100g
Name of column 135 is: bicarbonate_100g
Name of column 136 is: potassium_100g
Name of column 137 is: chloride_100g
Name of column 138 is: calcium_100g
Name of column 139 is: phosphorus_100g
Name of column 140 is: iron_100g
Name of column 141 is: magnesium_100g
Name of column 142 is: zinc_100g
Name of column 143 is: copper_100g
Name of column 144 is: manganese_100g
Name of column 145 is: fluoride_100g
Name of column 146 is: selenium_100g
Name of column 147 is: chromium_100g
Name of column 148 is: molybdenum_100g
Name of column 149 is: iodine_100g
Name of column 150 is: caffeine_100g
Name of column 151 is: taurine_100g
Name of column 152 is: ph_100g
Name of column 153 is: fruits-vegetables-nuts_100g
Name of column 154 is: fruits-vegetables-nuts-estimate_100g
Name of column 155 is: collagen-meat-protein-ratio_100g
Name of column 156 is: cocoa_100g
Name of column 157 is: chlorophyl_100g
Name of column 158 is: carbon-footprint_100g
Name of column 159 is: nutrition-score-fr_100g
Name of column 160 is: nutrition-score-uk_100g
Name of column 161 is: glycemic-index_100g
Name of column 162 is: water-hardness_100g

### Step 8. What is the name of 105th column?

In [64]:
print(f" the name of the 105th column is: {food.iloc[:,104].name}")

 the name of the 105th column is: -glucose_100g

### Step 9. What is the type of the observations of the 105th column?

In [65]:
food.iloc[:,104].dtype

dtype('float64')

### Step 10. How is the dataset indexed?

In [66]:
print(food.index)

RangeIndex(start=0, stop=356027, step=1)

### Step 11. What is the product name of the 19th observation?

In [69]:
food["product_name"].iloc[18]

'Lotus Organic Brown Jasmine Rice'